n = float(input('Digite o número para a tabuada : '))
print('=='*10)
print('{} x {} = {}'.format(n, 1.0, n*1))
print('{} x {} = {}'.format(n, 2.0, n*2))
print('{} x {} = {}'.format(n, 3.0, n*3))
print('{} x {} = {}'.format(n, 4.0, n*4))
print('{} x {} = {}'.format(n, 5.0, n*5))
print('{} x {} = {}'.format(n, 6.0, n*6))
print('{} x {} = {}'.format(n, 7.0, n*7))
print('{} x {} = {}'.format(n, 8.0, n*8))
print('{} x {} = {}'.format(n, 9.0, n*9))
print('{} x {} = {}'.format(n, 10.0, n*10))
print('=='*10)
